name: Toolbox pipeline

on:
  push:

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Running Detekt
        run: ./gradlew detekt --no-daemon

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
      - name: Running ktlint
        run: ./gradlew ktlintCheck --no-daemon